# Generated by Django 2.1.7 on 2026-03-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='category',
            field=models.CharField(choices=[('Grains', 'Grains'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Organic', 'Organic')], max_length=50),
        ),
    ]
